/*
Making a HTTP request to get the JSON generated by hugo-lunr. This is using fetch which 
might not work on old IE
*/
if ((window.location.pathname == "/pages/search/")) {
  var lunrIndex, allPosts;
  fetch("/js/lunr.json")
    .then(response => {
      return response.json();
    })
    .then(response => {
      allPosts = response;
      lunrIndex = lunr(function() {
        this.field("title", {
          boost: 10
        });
        this.field("tags", {
          boost: 5
        });

        // ref is the result item identifier (I chose the page URL)         
        this.ref("uri");
        for (var i = 0; i < response.length; ++i) {
          this.add(response[i]);
        }
      });
    })
    .catch(error => {
      console.error(error);
    });


/*
Once we have the response we are initializing lunr. The fields that we pass into lunr 
must match the fields present in the JSON file. Then we loop through the JSON array and 
add each object into lunr.
*/
  document.getElementById("search-button").onclick = function() {
    search();
  };


/*
Onclick handler for search button
When we call search, we will call the search function on lunr with the parameters from 
the input. Lunr is going to return an array containing a score and URL. We are using the 
filter function to match that with the items from the response (saved in allposts) so 
that we can grab the title as well.
I am doing another filter at the end to remove all the null elements. 
*/
  function search() {
    document.getElementById("results").innerHTML = "";
    let query = document.getElementById("search-field").value;
    let results = lunrIndex.search(query).map(result => {
      return allPosts.filter(page => {
        return page.uri === result.ref && result.score > 4;
      })[0];
    });
    let totalResults;
    results = results.filter(p => {
      if (p) {
        return true;
      }
    });


/*
Write the output to the DOM
*/
    document.createElement("h1");
    for (let i = 0; i < 20 && i < results.length; i++) {
      let header = document.createElement("h2");
      let anchor = document.createElement("a");
      anchor.setAttribute("href", results[i].uri);
      anchor.innerText = results[i].title;
      header.appendChild(anchor);
      document.getElementById("results").appendChild(header);
      document.getElementById("found").innerText = `Found ${
        results.length
      } results - showing ${i + 1}`;
    }
  }
  document
    .getElementById("search-field")
    .addEventListener("keydown", function(event) {
      if (event.key === "Enter") {
        event.preventDefault();
        search();
      }
    });
}